name: Deployment Workflow
on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PEM_CONTENT }}  # Ensure this secret contains the new private key

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@deploy-aws.com "
          cd deploy_dir
          sudo rm -r Tsubakimoto_backend
          git clone https://isara40618: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@github.com/isaranakavisute/Tsubakimoto_backend.git 
          git checkout production
          git fetch
          git pull
          docker build -t isara40618/githubaction_image .
          "